apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-sentimentanalysis-api
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-sentimentanalysis-api
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: PradeepLoganathan
  - name: gitops_repository_name
    value: tap-gitops
  - name: gitops_ssh_secret
    value: gitops-https
  source:
    git:
      url: https://github.com/PradeepLoganathan/SentimentAnalysisAPI.git
      ref:
        branch: main